version: '3.9'

services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --reload # --reload only for dev
    restart: always
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_SECONDS: ${ACCESS_TOKEN_EXPIRE_SECONDS}
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    expose:
      - "5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_EXTENSIONS: ${POSTGRES_EXTENSIONS}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 6
  # test-db:
  #   image: postgres:16-alpine
  #   restart: always
  #   ports:
  #     - 5433:5432
  #   expose:
  #     - "5433"  
  #   volumes:
  #     - ./postgres/data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
  #     POSTGRES_USER: ${TEST_POSTGRES_USER}
  #     POSTGRES_DB: ${TEST_POSTGRES_DB}
  #     POSTGRES_EXTENSIONS: ${TEST_POSTGRES_EXTENSIONS}
  #     POSTGRES_HOST_AUTH_METHOD: scram-sha-256
  #     POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
volumes:
  cs-postgres:
  # test-cs-postgres:  